---
apiVersion: v1
kind: Service
metadata:
   name: test_problem1
  namespace: test
spec:
  ports:
  - port: 80
    nodePort: 31001
    targetPort: 80
    protocol: TCP
  selector:
    app: test_problem1
  type: NodePort
  
    
